### ISSUE TITLE
Serialization functions

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/RedditHubble#107]
We need utils to let go node converting from/to serialized form 

- Type.X[] to bytes memory txs
- txs to Type.X[]
- We also want those utils testable in TS

The rollupUtils we have now.
```
        BytesFromX
        BytesFromXNoStruct
        XFromBytes
        XSignBytes
        CompressX
        CompressXNoStruct
        CompressXWithMessage
        DecompressX
```

**Comment by ChihChengLiang** [comment]
@vaibhavchellani  Can you confirm to the requirement from the go-node?

**Comment by vaibhavchellani** [comment]
Yeah this is correct.

**Comment by ChihChengLiang** [comment]
Outdated
