### ISSUE TITLE
Optimise submit batch

### ISSUE THREAD

**Issue by vaibhavchellani** [thehubbleproject/RedditHubble#140]
We are introducing several changes to how we commit state. 
1. Submitting multiple commitments in a single batch to amortize the cost. 
2. Reducing the state commitment to a single hash to occupy less storage
3. Submitting txRoot optimistically. 

All ideas and possible implementation level detail being outlined [here](https://hackmd.io/d2P5j5R-QreI4NDdoqewaw)

**Comment by ChihChengLiang** [comment]
Fixed in #155
