### ISSUE TITLE
Apply Tx checks if stateIndex == pubkeyIndex

### ISSUE THREAD

**Issue by kilic** [thehubbleproject/RedditHubble#147]
https://github.com/thehubbleproject/RedditHubble/blob/173136790f4b82f997e747612dc0eb9054326839/contracts/FraudProof.sol#L138 

Here we compare `fromIndex` which is state index and account.ID  which is pubkey index.
From `merkle_proof` it's not possible to know if account is sender or receiver. Then I suggest to applying tx in `processBatch` rather than in separate functions or use `senderApplyTx` and `receiverApplyTx`

**Comment by ChihChengLiang** [comment]
On a side note, we currently do the transfer like this:
```
validate_witness(sender)
applyTx(sender)
validate_witness(receiver)
applyTx(receiver)
```
But this has a problem described in this issue. Also, it requires the client-side to get witnesses from the database twice.

It should be fine if we do:
```
validate_witness(sender)
validate_witness(receiver)
applyTx(sender, receiver)
```

**Comment by vaibhavchellani** [comment]
We cannot do that, because that would allow people to double spend if they send a transaction to themselves. 

The client already applies sender and then does witness generation for receiver.

**Comment by vaibhavchellani** [comment]
> From merkle_proof it's not possible to know if account is sender or receiver. Then I suggest to applying tx in processBatch rather than in separate functions or use senderApplyTx and receiverApplyTx


I think we can detect if the account we are applying from is the sender or receiver by doing the following check:
```
if tx.fromIndex == accouMP.path {
// decrease balance
// increment nonce
}

if tx.toIndex == accountMP.path {
// increase balance
// increment nonce
}
```

What do you guys think @ChihChengLiang @kilic

**Comment by kilic** [comment]
As it is noted in https://github.com/thehubbleproject/contracts/issues/94 `accountMP.path` should be gone we should only detect sender and receiver from transaction data.

**Comment by vaibhavchellani** [comment]
`account.Path` is part of account merkle proof and cannot be removed I think. And it here it just used to detect if the `indexes` in transactions are `from` or `to`. 

The indexes in transaction are stateID's are so is the path in accountMP, so this should be a valid check.

AFAIK for fixing [this issue](https://github.com/thehubbleproject/contracts/issues/94) we need to make sure that the account.Path in fromAccountMP is the fromIndex in the transaction and account.Path in toAccountMP is the toIndex in the transaction.

**Comment by kilic** [comment]
We get `stateIndex` data from _tx_ and `pubkeyIndex` from _account data preimage_.

So, merkle proof structs do not have to include paths because it is redundant and you would need to always check if tx data or account data is satisfies the explicitly given path which is annoying.

**Comment by vaibhavchellani** [comment]
> So, merkle proof structs do not have to include paths because it is redundant and you would need to always check if tx data or account data satisfies the explicitly given path which is annoying.


Agree on the point that we can use the StateIndex from Tx directly and save on the checks. 

Would like to brainstorm on using `ApplyTx()` as we are now, do you have any ideas?

**Comment by vaibhavchellani** [comment]
Maybe, for now, we can keep the 2 redundant variables and 2 checks as optimizing fraud-proof isn't a priority.

**Comment by kilic** [comment]
Before we come to optimization I feel like these indexes for different trees are constant source of confusion. 
We already have three problems on these including this one and others:
https://github.com/thehubbleproject/contracts/issues/94
https://github.com/thehubbleproject/contracts/issues/95

**Comment by vaibhavchellani** [comment]
Yep, sounds like a good place to start. 

Let me fix this in the project documentation once and for all. Sharing link in a few mins.

**Comment by barryWhiteHat** [comment]
I think that having two trees is very important for mass migration and keeping data availabilty costs low for different apps.

**Comment by vaibhavchellani** [comment]
Yep, we are just asking for fixing the terminology to avoid confusion.

**Comment by ChihChengLiang** [comment]
I think we don't worry about this for a while after #180
