### ISSUE TITLE
Account root is not required for batch processing

### ISSUE THREAD

**Issue by kilic** [thehubbleproject/RedditHubble#164]
https://github.com/thehubbleproject/RedditHubble/blob/173136790f4b82f997e747612dc0eb9054326839/contracts/rollupReddit.sol#L273

**Comment by ChihChengLiang** [comment]
Is the reason we batch processing doesn't require account root because we check the public key inclusion proof when disputing signature?  https://github.com/thehubbleproject/RedditHubble/pull/166

**Comment by kilic** [comment]
> Is the reason we batch processing doesn't require account root because we check the public key inclusion proof when disputing signature? #166

Yes, that's why we don't need account root there.
