### ISSUE TITLE
Incorrect state root comparison after transition

### ISSUE THREAD

**Issue by kilic** [thehubbleproject/RedditHubble#177]
After transition is performed with committed transactions comparison is applyied against __old__ stateRoot.
 https://github.com/thehubbleproject/RedditHubble/blob/59affd3e26ac8c2f9c9ff945ad3b376e9e3d1c68/contracts/rollup.sol#L367
https://github.com/thehubbleproject/RedditHubble/blob/59affd3e26ac8c2f9c9ff945ad3b376e9e3d1c68/contracts/rollup.sol#L387

How it should be like:

* Case 1, dispute targeted 0th commitment: we need to compare against final state root of previous batch.
* Case 2, dispute targeted nth commitment: then we must compare against (n-1)th state root of same batch.

With both cases we need to reveal two consecutive state roots commitements in order to detect invalid transition

**Comment by vaibhavchellani** [comment]
Ah! Yep, this is a valid bug.
