### ISSUE TITLE
Rename processBatch to processCommit

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/RedditHubble#198]
We used to submit a batch of transactions and then dispute the same batch of transactions.

But now a batch consists of many commits, with each represents state transitions of many transactions.

The `disputeBatch` function still dispute a batch and roll it back if it's fraudulent. But the `processBatch` now only process transactions in a commitment. So we should rename `processBatch` to `processCommit` for clarity.

**Comment by vaibhavchellani** [comment]
I agree!
