### ISSUE TITLE
Monthly Burn

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/RedditHubble#2]
This has two parts

- User sent consent to burn
- At the end of the month, coordinator executes the burn

**Comment by ChihChengLiang** [comment]
Need to update nonce to the burn consent to prevent replay attack.

**Comment by barryWhiteHat** [comment]
We also need soemthing to ensure that the monthly burn happens just once per month. So another nonce type variable that stores the current epoch that was airdroped and prevents aidrop if epoch < leaf.currnet_epoch
