### ISSUE TITLE
Remove airdrop, burn exec, burn consent, and create account.

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/RedditHubble#212]
These are not the recent priority and probably a burden to maintain those.

**Comment by barryWhiteHat** [comment]
I think we still need create account tho ?

**Comment by ChihChengLiang** [comment]
Post the offline discussion summary for the @barryWhiteHat's question here. 
We'll have a new Pay to public key feature that has a part functions like create account. We'll either implement a merge of  create account + transfer into the current Transfer.sol, or we implement a new PayToPubkey.sol. Either way, the result will look very different from the existing create account, so it can be removed now.
