### ISSUE TITLE
Interfaces for batch

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/RedditHubble#30]
- The current `rollup.sol::disputeBatch` takes Types.Transaction[] as input. We want another interface to fit the Reddit Txs
- We want to perform batch level operations. For example, we want to specify `form` address at batch level to represent all the transactions in the batch have same `form` address. And we want to validate that batch level information in the fraud proof. We need to change `FraudProof.sol::processBatch` for that.

**Comment by vaibhavchellani** [comment]
Yeah this is something that I wanted to discuss a bit about too. What do you think about the following:
1. Each application or tx type has a separate contract which consists of the following:
- ProcessTx 
- ProcessBatch
- Dispute function

2. On the core contract we just have submitBatch's and processTx's for all txTypes. 

I am afraid common interfaces would be a little hard and inefficient, but I may be wrong, what do you have in mind @ChihChengLiang

**Comment by barryWhiteHat** [comment]
Can we do this by having a differnt commitment decompression.
Currently the decompression takes teh to , from , amount and marshales it into variable. 

I propose the decompression takes to , amount and then batch level from and marshels them into variables. 

Is this a good solution , or are you already factoring this in?

**Comment by ChihChengLiang** [comment]
Follow up here #79
