### ISSUE TITLE
Dependency not found for ethers-contracts

### ISSUE THREAD

**Issue by wdcs-amitkumar** [thehubbleproject/RedditHubble#694]
Hello Team !

I tried to run the testcasse for BLStest but found that some dependency is missing
``` types/ethers-contracts ```

refernce : https://github.com/thehubbleproject/hubble-contracts/blob/f1c13fe4e1a0dc9ab1f150895de7c0e654ee46b0/test/fast/bls.test.ts#L1

**Comment by jacque006** [comment]
Hey @amitcz ,

You likely need to call `npm run generate` to generate typechain types.

From a fresh repo clone:

```sh
npm i
npm run generate
npm test -- ./test/fast/bls.test.ts
```
